### ISSUE TITLE
.topcard should be inside of .card

### ISSUE THREAD

**Issue by nicolasjuarezn** [nutsil/learning-react#3]
You will notice when you move .topcard inside of .card that your flex will tweak your designs, in order to solve this you could apply `flex-wrap: wrap` on the .card container and `width: 100%` on the .topcard element

https://github.com/nutsil/learning-react/blob/5c39ff9251cb834df2a3dc5f0c05f843031a2581/src/App.js#L11

**Comment by nutsil** [comment]
Fixed

**Comment by nicolasjuarezn** [comment]
.topcard class shouldn't have margin property

**Comment by nicolasjuarezn** [comment]
Also remove the height of .card class

**Comment by nicolasjuarezn** [comment]
LGTM
