### ISSUE TITLE
Create a container element div for the image and the information details

### ISSUE THREAD

**Issue by nicolasjuarezn** [nutsil/learning-react#4]
Keep in mind that we need to think HTML as block building

https://github.com/nutsil/learning-react/blob/5c39ff9251cb834df2a3dc5f0c05f843031a2581/src/App.js#L14

**Comment by nutsil** [comment]
Fixed

**Comment by nicolasjuarezn** [comment]
LGTM but always keep in mind to avoid as possible the fixed sizes
